[package]
name = "gradient-slider"
version = "0.1.0"
entrypoint = "gradient-slider.typ"
authors = ["Johannes Brandenburger <@johannesbrandenburger>"]
license = "MIT"
keywords = ["slider"]
categories = ["components"]
exclude = ["examples"]
description = "Simple component to show a value between 0 and 1 on a nice slider"
